name: 'ServiceNow DevOps Change'
description: 'Create Change Requests in ServiceNow DevOps'
inputs:
  devops-integration-user-name:
    description: 'DevOps Integration User Name'
    required: true
  devops-integration-user-pass:
    description: 'DevOps Integration User Pass'
    required: true
  instance-name: 
    description: 'ServiceNow Instance Name (e.g.: rapdevio)'
    required: true
  tool-id:
    description: 'Orchestration tool id'
    required: true
  context-github:
    description: 'Github context'
    required: true
  callback-repo:
    description: 'Callback repo'
    required: true
  callback-pipeline-id:
    description: 'Callback pipeline ID'
    required: true
  callback-params:
    description: 'Callback params'
    required: true
branding:
  icon: 'arrow-right-circle'
  color: 'blue'
runs: 
  using: 'node12'
  main: 'dist/index.js'
